import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { sveltePreprocess } from 'svelte-preprocess';
import builtins from 'builtin-modules';
import { resolve } from 'path';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Custom plugin to copy files from dist/ to root after build
// This works around Rollup's watch mode limitation (input can't be inside output directory)
const copyToRoot = () => ({
	name: 'copy-to-root',
	writeBundle() {
		const filesToCopy = ['main.js', 'styles.css'];
		for (const file of filesToCopy) {
			const srcPath = resolve(__dirname, 'dist', file);
			const destPath = resolve(__dirname, file);
			if (fs.existsSync(srcPath)) {
				fs.copyFileSync(srcPath, destPath);
				console.log(`Copied ${file} to root`);
			}
		}
	},
});

export default defineConfig(({ mode }) => {
	const isProduction = mode === 'production';

	return {
		define: {
			__DEV__: JSON.stringify(!isProduction),
		},
		resolve: {
			alias: {
				'@/*': resolve(__dirname, './src/*'),
				'@': resolve(__dirname, './src'),
			},
		},
		build: {
			lib: {
				entry: resolve(__dirname, 'src/main.ts'),
				formats: ['cjs'],
				fileName: () => 'main.js',
			},
			outDir: 'dist',
			emptyOutDir: true,
			cssCodeSplit: false,
			minify: isProduction,
			sourcemap: isProduction ? false : 'inline',
			rollupOptions: {
				external: [
					'obsidian',
					'electron',
					'@codemirror/autocomplete',
					'@codemirror/collab',
					'@codemirror/commands',
					'@codemirror/language',
					'@codemirror/lint',
					'@codemirror/search',
					'@codemirror/state',
					'@codemirror/view',
					'@lezer/common',
					'@lezer/highlight',
					'@lezer/lr',
					...builtins,
				],
				output: {
					banner: banner,
					assetFileNames: 'styles.css',
				},
			},
		},
		plugins: [
			svelte({
				preprocess: sveltePreprocess({
					typescript: {
						tsconfigFile: 'tsconfig.svelte.json',
					},
				}),
				compilerOptions: {
					dev: !isProduction,
				},
			}),
			copyToRoot(),
		],
	};
});
