export const tokens = {
	'text-normal': 'var(--text-normal)',
	'text-muted': 'var(--text-muted)',
	'text-faint': 'var(--text-faint)',
	'text-accent': 'var(--text-accent)',
	'text-error': 'var(--text-error)',
	'text-warning': 'var(--text-warning)',
	'text-success': 'var(--text-success)',
	'text-accent-foreground': 'var(--text-on-accent)',

	red: 'var(--color-red)',
	orange: 'var(--color-orange)',
	yellow: 'var(--color-yellow)',
	green: 'var(--color-green)',
	cyan: 'var(--color-cyan)',
	blue: 'var(--color-blue)',
	purple: 'var(--color-purple)',
	pink: 'var(--color-pink)',

	'background-primary': 'var(--background-primary)',
	'background-primary-alt': 'var(--background-primary-alt)',
	'background-secondary': 'var(--background-secondary)',
	'background-secondary-alt': 'var(--background-secondary-alt)',
	'background-tertiary': 'var(--background-tertiary)',
	'background-tertiary-alt': 'var(--background-tertiary-alt)',

	'background-modifier-border': 'var(--background-modifier-border)',
	'background-modifier-border-focus': 'var(--background-modifier-border-focus)',
	'background-modifier-border-hover': 'var(--background-modifier-border-hover)',
	'background-modifier-hover': 'var(--background-modifier-hover)',
	'background-modifier-active': 'var(--background-modifier-active)',
	'background-modifier-active-hover': 'var(--background-modifier-active-hover)',
	'background-modifier-error': 'var(--background-modifier-error)',
	'background-modifier-error-hover': 'var(--background-modifier-error-hover)',
	'background-modifier-selected': 'var(--background-modifier-selected)',
	'background-modifier-form-field': 'var(--background-modifier-form-field)',
	'background-modifier-form-field-hover': 'var(--background-modifier-form-field-hover)',
	'background-modifier-settings': 'var(--setting-items-background)',
	'background-modifier-settings-border': 'var(--setting-items-border-color)',

	'interactive-accent': 'var(--interactive-accent)',
	'interactive-accent-hover': 'var(--interactive-accent-hover)',
	'interactive-normal': 'var(--interactive-normal)',
	'interactive-hover': 'var(--interactive-hover)',

	'status-info': 'var(--color-blue)',
	'status-success': 'var(--color-green)',
	'status-warning': 'var(--color-orange)',
	'status-error': 'var(--color-red)',

	'font-interface': 'var(--font-interface)',
	'font-monospace': 'var(--font-monospace)',
	'font-text': 'var(--font-text)',
} as const;
